import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import Providers from './provider';
import './globals.css';

const notoSans = Noto_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'CHECKUREE',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <title>CHECKUREE</title>
                <link
                    href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined&display=block"
                    rel="stylesheet"
                />
            </head>
            <body className={notoSans.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
